spring:
  datasource:
    url: jdbc:h2:mem:quoteservice
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:db/init.xml